# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'AnsibleConnection'
    playbookSourceRemoteMachine: 'ansibleMachine'
    playbookPathAnsibleMachineOnRemoteMachine: './play.yaml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'agentMachine'
    inventoryFileLinkedArtifactOnRemoteMachine: './inventory'
    args: --extra-vars package=$(DEPENDENCY)